# Generated by Django 3.0.5 on 2020-08-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_text', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_phrase', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_votes', models.IntegerField()),
                ('sum_votes', models.IntegerField()),
                ('avg_point', models.FloatField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoNameApp.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoNameApp.Poll')),
            ],
            options={
                'unique_together': {('poll', 'choice')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=1)),
                ('phone_number', models.CharField(default=None, max_length=12, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('birthday', models.DateTimeField(default=None)),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoNameApp.User'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(choices=[('-5', -5), ('-4', -4), ('-3', -3), ('-2', -2), ('-1', -1), ('0', 0), ('+1', 1), ('+2', 2), ('+3', 3), ('+4', 4), ('+5', 5)])),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
                ('poll_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoNameApp.PollChoice')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoNameApp.User')),
            ],
            options={
                'unique_together': {('poll_choice', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='NoNameApp.User')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='NoNameApp.User')),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
